// <auto-generated />
using BancoDados_Kasaleve_SistemaTudo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDados_Kasaleve_SistemaTudo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260318192104_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", b =>
                {
                    b.Property<int>("tipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tipoProdutoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoProdutoId"));

                    b.Property<string>("tipoProdutoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoProdutoNome");

                    b.HasKey("tipoProdutoId");

                    b.ToTable("TipoProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
