// <auto-generated />
using System;
using BancoDados_Kasaleve_SistemaTudo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDados_Kasaleve_SistemaTudo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260701134827_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cargoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("CargoId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpfCnpj");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("endereco");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sobrenome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", b =>
                {
                    b.Property<int>("OrcamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orcamentoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcamentoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    b.Property<string>("CorAluminio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("corAluminio");

                    b.Property<string>("CorCorda")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("corCorda");

                    b.Property<string>("CorTecido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("corTecido");

                    b.Property<DateTime>("DataOrcamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataOrcamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TermosCondicoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("termosCondicoes");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valorFrete");

                    b.Property<int>("VendedoraId")
                        .HasColumnType("int")
                        .HasColumnName("vendedoraId");

                    b.HasKey("OrcamentoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendedoraId");

                    b.ToTable("Orcamento");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.OrcamentoItem", b =>
                {
                    b.Property<int>("OrcamentoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orcamentoItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcamentoItemId"));

                    b.Property<string>("DescricaoItem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricaoItem");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int")
                        .HasColumnName("orcamentoId");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valorUnitario");

                    b.HasKey("OrcamentoItemId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("OrcamentoItem");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.PrecoProduto", b =>
                {
                    b.Property<int>("PrecoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("precoProdutoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrecoProdutoId"));

                    b.Property<DateTime?>("DataVigenciaFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataVigenciaFim");

                    b.Property<DateTime>("DataVigenciaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataVigenciaInicio");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    b.Property<int?>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("PrecoProdutoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("PrecoProduto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("LONGBLOB")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<int?>("TipoProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("tipoProdutoId");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("ProdutoId");

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tarefaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarefaId"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacao");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataVencimento");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("titulo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", b =>
                {
                    b.Property<int>("TipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tipoProdutoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoProdutoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("TipoProdutoId");

                    b.ToTable("TipoProduto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("cargoId");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senhaHash");

                    b.Property<int?>("VendedoraId")
                        .HasColumnType("int")
                        .HasColumnName("vendedoraId");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CargoId");

                    b.HasIndex("VendedoraId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", b =>
                {
                    b.Property<int>("VendedoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vendedoraId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedoraId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("VendedoraId");

                    b.ToTable("Vendedora");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Cliente", "Cliente")
                        .WithMany("Orcamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", "Vendedora")
                        .WithMany("Orcamentos")
                        .HasForeignKey("VendedoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedora");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.OrcamentoItem", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", "Orcamento")
                        .WithMany("OrcamentoItens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Produto", "Produto")
                        .WithMany("OrcamentoItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.PrecoProduto", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Produto", "Produto")
                        .WithMany("PrecosProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", null)
                        .WithMany("PrecosProdutos")
                        .HasForeignKey("TipoProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Produto", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId");

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Tarefa", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Usuario", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", "Vendedora")
                        .WithMany("Usuarios")
                        .HasForeignKey("VendedoraId");

                    b.Navigation("Cargo");

                    b.Navigation("Vendedora");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cliente", b =>
                {
                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", b =>
                {
                    b.Navigation("OrcamentoItens");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Produto", b =>
                {
                    b.Navigation("OrcamentoItens");

                    b.Navigation("PrecosProdutos");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", b =>
                {
                    b.Navigation("PrecosProdutos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Usuario", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
