// <auto-generated />
using BancoDados_Kasaleve_SistemaTudo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDados_Kasaleve_SistemaTudo.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cargo", b =>
                {
                    b.Property<int>("cargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cargoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cargoId"));

                    b.Property<string>("cargoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cargoNome");

                    b.HasKey("cargoId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clienteId"));

                    b.Property<string>("clienteCEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteCEP");

                    b.Property<string>("clienteCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteCPF");

                    b.Property<string>("clienteCyti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteCyti");

                    b.Property<string>("clienteEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteEmail");

                    b.Property<string>("clienteEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteEnd");

                    b.Property<string>("clienteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteNome");

                    b.Property<string>("clienteRG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteRG");

                    b.Property<string>("clienteTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clienteTel");

                    b.HasKey("clienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Logim", b =>
                {
                    b.Property<int>("LogimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logimId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogimId"));

                    b.Property<string>("LogimEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logimEmail");

                    b.Property<string>("LogimNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logimNome");

                    b.Property<string>("LogimSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logimSenha");

                    b.Property<int>("cargoId")
                        .HasColumnType("int");

                    b.HasKey("LogimId");

                    b.HasIndex("cargoId");

                    b.ToTable("logim");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", b =>
                {
                    b.Property<string>("orcamentoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("orcamentoId");

                    b.Property<int?>("Nonce")
                        .HasColumnType("int")
                        .HasColumnName("dataOrcamento");

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("orcamentoCorCorda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orcamentoCorCorda");

                    b.Property<string>("orcamentoCorTecido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orcamentoCorTecido");

                    b.Property<string>("orcamnetoCorAluminio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orcamnetoCorAluminio");

                    b.Property<int>("praiceId")
                        .HasColumnType("int");

                    b.Property<int>("vendedoraId")
                        .HasColumnType("int");

                    b.HasKey("orcamentoId");

                    b.HasIndex("clienteId");

                    b.HasIndex("praiceId");

                    b.HasIndex("vendedoraId");

                    b.ToTable("Orcamento");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Praice", b =>
                {
                    b.Property<int>("praiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("praiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("praiceId"));

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("praiceValor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("praiceValor");

                    b.HasKey("praiceId");

                    b.HasIndex("TipoProdutoId");

                    b.ToTable("Praice");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Produto", b =>
                {
                    b.Property<int>("produtoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("produtoId"));

                    b.Property<string>("produtoFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("produtoFoto");

                    b.Property<string>("produtoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("produtoNome");

                    b.Property<decimal>("produtoValor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("produtoValor");

                    b.HasKey("produtoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", b =>
                {
                    b.Property<int>("tipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tipoProdutoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoProdutoId"));

                    b.Property<string>("tipoProdutoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoProdutoNome");

                    b.HasKey("tipoProdutoId");

                    b.ToTable("TipoProduto");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", b =>
                {
                    b.Property<int>("vendedoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vendedoraId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vendedoraId"));

                    b.Property<string>("vendedoraNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vendedoraNome");

                    b.HasKey("vendedoraId");

                    b.ToTable("Vendedora");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Logim", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("cargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Orcamento", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Praice", "Praice")
                        .WithMany()
                        .HasForeignKey("praiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.Vendedora", "Vendedora")
                        .WithMany()
                        .HasForeignKey("vendedoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Praice");

                    b.Navigation("Vendedora");
                });

            modelBuilder.Entity("BancoDados_Kasaleve_SistemaTudo.Models.Praice", b =>
                {
                    b.HasOne("BancoDados_Kasaleve_SistemaTudo.Models.TipoProduto", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
